dist: trusty
sudo: require

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - cmake
      - valgrind
      - cppcheck
      - doxygen
      - graphviz

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

  - cd ${TRAVIS_BUILD_DIR}
  - chmod +x deploy.sh
  - ./deploy.sh
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install
  - gem install coveralls-lcov
  - lcov --version
  - g++ --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters
  - chmod +x wmake

script:
  - cd ${TRAVIS_BUILD_DIR}
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Compile project and run tests
  - ./wmake build
  - ./wmake test
  # Run static code analyzer
  - cppcheck lib
  # Run valgrind to detect memory bugs
  - valgrind --leak-check=full --error-exitcode=2 ./bin/tests/tests

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' '/include/*' 'examples/*' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov coverage.info

env:
  global:
    - ENCRYPTION_LABEL: "0b154c48edef"
    - COMMIT_AUTHOR_EMAIL: "deep@deepdhillon.ca"
