dist: trusty
sudo: require

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - cmake
      - valgrind
      - cppcheck

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Compile project and run tests
  - chmod +x wmake
  - ./wmake build
  - ./wmake run
  # Run static code analyzer
  - cppcheck wlib
  # Run valgrind to detect memory bugs
  - valgrind --leak-check=full ./bin/tests/Tests
